apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: migration-x
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  destination:
    name: ''
    namespace: migrations
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: https://migrations-test-repo.storage.googleapis.com/
    targetRevision: {{ .Values.migration_version | quote }}
    chart: migrations
